@startuml merchants-create-deal
!include skinparam.puml

actor Merchant as mer
participant "App" as app
participant "API" as api
participant "ms-deals" as msd

mer -[#blue]> app ++: "Create deal" page
app -[#blue]> api ++: deals.create()
api -[#red]> api: auth
api -[#red]> msd ++: createDeal()
msd -[#red]-> api: "success"
api -[#blue]-> app: "success"
app -[#blue]-> mer: "Deal successfully\ncreated" page

@enduml